### ISSUE TITLE
<Title />

### ISSUE THREAD

**Issue by tetuaoro** [Baptistemontan/leptos_i18n#135]
# Description

Seems `<Title />` does not work with `t!` macro.

```yaml
# tao.yml
title: "Some text {{ q }}"
```

```rust
let tao = move || String::from("Hello Title");
let title = t!(i18n, tao.title, q = tao);

view! {
    <Title text=title/>
}
```

## Error Ouput

The `text` field doesn't satisfied.

```bash
the trait bound `Oco<'static, str> ... does not satisfied
```

### Cargo.toml
```toml
leptos = { version = "0.6", features = ["experimental-islands"] }
leptos_i18n = { version = "0.4.0", default-features = false, features = ["cookie", "experimental-islands", "track_locale_files", "yaml_files"] }
```

## Expected

Not error output and get `Some text Hello Title` in browser tab title.

## Fixed

Fixed using string concat :

```yaml
# tao.yml
# remove q
title: "Some text"
```

```rust
let tao = move || String::from("Hello Title");
let __title = t!(i18n, tao.title);
let title = move || format!("{} {}", __title(), tao());
```
