### ISSUE TITLE
Migrating from `i18n.json` to `Cargo.toml`

### ISSUE THREAD

**Issue by Baptistemontan** [Baptistemontan/leptos_i18n#25]
Currently the config file is `i18n.json`, but it would be better to put the configurations in the Cargo manifest, like `cargo-leptos` does it.

So instead of 

`i18n.json`:
```json
{
    "default": "en",
    "locales": ["en", "fr"]
}
```

we would have

`Cargo.toml`:
```toml
[package.metadata.i18n]
default = "en"
locales = ["en", "fr"]
```

This would be a breaking changes, but I would like to bring it to `v0.2.0`
