### ISSUE TITLE
Cannot load locales when inside a Workspace

### ISSUE THREAD

**Issue by francisbr** [Baptistemontan/leptos_i18n#53]
I get: `error: Could not found "[package.metadata.leptos-i18n]" in cargo manifest (Cargo.toml)`, when calling `leptos_i18n::load_locales!();`. I think there's a problem when trying to load the locales when inside a worspace? Or maybe I just missunderstood something and am placing my metadata in the wrong place?

Here is my folder structure:
```
frontend/
├─ api_sdk/
│  ├─ .../
├─ app/
│  ├─ src/
│  │  ├─ main.rs
│  │  ├─ ...
│  ├─ translations/
│  ├─ Cargo.toml
│  ├─ index.html
├─ Cargo.toml
```
The `app/` folder is where is my leptos code code and I am trying to use leptos_i18n. Here is my setup:
```toml
# frontend/Cargo.toml
[workspace]
resolver = "2"
members = ["app", "api_sdk"]
default-members = ["app"]
```

```toml
# frontend/app/Cargo.toml
[package]
name = "app"
version = "0.1.0"
edition = "2021"

[package.metadata.leptos-i18n]
default = "en"
locales = ["en", "fr"]
locales-dir = "./translations"

[dependencies.leptos]
version = "0.5.0-rc1"
features = ["csr", "tracing"]

[dependencies.leptos_i18n]
version = "0.2.0-beta5"
```

And so I am trying to call `leptos_i18n::load_locales!();` inside `frontend/app/src/main.rs` and I get the error specified.
