### ISSUE TITLE
`hydrate` and `ssr` features are incompatible

### ISSUE THREAD

**Issue by maneac** [Baptistemontan/leptos_i18n#82]
## Overview

The `hydrate` and `ssr` features define competing implementations of `fetch_locale`, so they cannot both be enabled at the same time.
For example, when enabling `leptos_i18n` in a multi-crate workspace environment, the following error is produced:

```sh
> cargo check
    Checking leptos_i18n v0.2.1
error[E0428]: the name `fetch_locale` is defined multiple times
  -->$CARGO_DIR/registry/src/index.crates.io-6f17d22bba15001f/leptos_i18n-0.2.1/src/fetch_locale.rs:10:1
   |
5  | pub fn fetch_locale<T: Locale>() -> T {
   | ------------------------------------- previous definition of the value `fetch_locale` here
...
10 | pub fn fetch_locale<T: Locale>() -> T {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `fetch_locale` redefined here
   |
   = note: `fetch_locale` must be defined only once in the value namespace of this module

For more information about this error, try `rustc --explain E0428`.
```

## Steps To Reproduce

1. Clone the Leptos Axum Workspace template: https://github.com/leptos-rs/start-axum-workspace 
  Latest commit at time of raising: `62ed4424dcc37ca75bbe6b236ce6427bf9cce296`
2. Add `leptos_i18n` as a dependency of the shared `app`. Full `app/Cargo.toml`:
```toml
[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }

http.workspace = true
cfg-if.workspace = true
thiserror.workspace = true
leptos_i18n = { version = "0.2.1", default-features = false, features = [
    "json_files",
] }

[features]
default = []
hydrate = [
    "leptos/hydrate",
    "leptos_meta/hydrate",
    "leptos_router/hydrate",
    "leptos_i18n/hydrate",
]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "leptos_i18n/axum",
    "dep:leptos_axum",
]
```
3. Run `cargo check` against the workspace

## Additional Information

This appears to be due to the way Cargo resolves features of shared dependencies: https://doc.rust-lang.org/cargo/reference/features.html#feature-unification. In this example above, both the `frontend` and `server` crates depend on `app`, but with different sets of features enabled. Cargo then _assumes_ these features are additive, attempts to build `app` with both the `hydrate` and `axum` (`ssr`) features enabled, producing the original error.

## Desired Outcome

The `hydrate` and `ssr` features can be enabled at the same time, and compile.

The following is a "functioning" version of `src/fetch_locale.rs`, but is relatively ugly and may have unintended consequences:
```rs
use crate::Locale;

#[cfg(all(feature = "ssr", not(feature = "hydrate")))]
#[inline]
pub fn fetch_locale<T: Locale>() -> T {
    crate::server::fetch_locale_server_side::<T>()
}

#[cfg(all(feature = "hydrate", not(feature = "ssr")))]
pub fn fetch_locale<T: Locale>() -> T {
    leptos::document()
        .document_element()
        .and_then(|el| el.get_attribute("lang"))
        .and_then(|lang| T::from_str(&lang))
        .unwrap_or_default()
}

#[cfg(any(
    all(feature = "hydrate", feature = "ssr"),
    not(any(
        feature = "ssr",
        feature = "hydrate",
        all(feature = "csr", feature = "cookie")
    ))
))]
#[inline]
pub fn fetch_locale<T: Locale>() -> T {
    Default::default()
}

#[cfg(all(feature = "csr", feature = "cookie"))]
pub fn fetch_locale<T: Locale>() -> T {
    fn inner<T: Locale>() -> Option<T> {
        let document = super::get_html_document()?;
        let cookies = document.cookie().ok()?;
        cookies.split(';').find_map(|cookie| {
            let (key, value) = cookie.split_once('=')?;
            if key.trim() == super::COOKIE_PREFERED_LANG {
                T::from_str(value)
            } else {
                None
            }
        })
    }
    inner().unwrap_or_default()
}
```
